/**
 * Modal form for creating a new service record for a car.
 * Fields: fecha_mantenimiento, km_mantenimiento, precio, notas.
 * Snapshot fields (car_matricula, car_tipo, etc.) are generated by the backend.
 */
import { useState } from 'react';
import { DialogActions, Button, TextField, Grid, Alert, InputAdornment } from '@mui/material';
import FormModal from '../../components/ui/FormModal';
import { createCarService } from '../../services/cars.service';

const EMPTY = {
  fecha_mantenimiento: '',
  km_mantenimiento: '',
  precio: '',
  notas: '',
};

export default function CarServiceFormModal({ open, onClose, carId, onSaved }) {
  const [form, setForm] = useState(EMPTY);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  const set = (field) => (e) => setForm((f) => ({ ...f, [field]: e.target.value }));

  const handleOpen = () => {
    setForm(EMPTY);
    setError('');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.fecha_mantenimiento) {
      setError('La fecha de mantenimiento es requerida');
      return;
    }
    setSaving(true);
    setError('');
    try {
      await createCarService(carId, {
        fecha_mantenimiento: form.fecha_mantenimiento,
        km_mantenimiento: form.km_mantenimiento ? Number(form.km_mantenimiento) : null,
        precio: form.precio ? Number(form.precio) : null,
        notas: form.notas || null,
      });
      onSaved();
      onClose();
    } catch (err) {
      setError(err.response?.data?.message || 'Error al registrar servicio');
    } finally {
      setSaving(false);
    }
  };

  return (
    <FormModal
      open={open}
      onClose={onClose}
      title="Registrar servicio"
      onTransitionEnter={handleOpen}
    >
      <form onSubmit={handleSubmit}>
        <Grid container spacing={2} sx={{ mt: 0.5 }}>
          {error && (
            <Grid size={12}>
              <Alert severity="error">{error}</Alert>
            </Grid>
          )}

          <Grid size={{ xs: 12, sm: 6 }}>
            <TextField
              label="Fecha de mantenimiento"
              type="date"
              value={form.fecha_mantenimiento}
              onChange={set('fecha_mantenimiento')}
              required
              fullWidth
              slotProps={{ inputLabel: { shrink: true } }}
            />
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <TextField
              label="Kilómetros"
              type="number"
              value={form.km_mantenimiento}
              onChange={set('km_mantenimiento')}
              fullWidth
              slotProps={{
                input: {
                  endAdornment: <InputAdornment position="end">km</InputAdornment>,
                },
              }}
            />
          </Grid>

          <Grid size={{ xs: 12, sm: 6 }}>
            <TextField
              label="Precio"
              type="number"
              value={form.precio}
              onChange={set('precio')}
              fullWidth
              slotProps={{
                input: {
                  startAdornment: <InputAdornment position="start">$</InputAdornment>,
                },
              }}
            />
          </Grid>

          <Grid size={12}>
            <TextField
              label="Notas"
              value={form.notas}
              onChange={set('notas')}
              fullWidth
              multiline
              minRows={3}
            />
          </Grid>
        </Grid>

        <DialogActions sx={{ px: 0, pt: 2 }}>
          <Button onClick={onClose}>Cancelar</Button>
          <Button type="submit" variant="contained" disabled={saving}>
            {saving ? 'Guardando…' : 'Registrar'}
          </Button>
        </DialogActions>
      </form>
    </FormModal>
  );
}
